### ISSUE TITLE
OperationalError('SSL SYSCALL error: EOF detected\\n',)

### ISSUE THREAD

**Issue by funkybob** [gmcguire/django-db-pool#9]
We deployed this wonderful tool to one of our app servers yesterday, and it worked fine for a day, so we deployed to the other 16 servers today.

Now we're infrequently getting the above error from both Django and Celery.

Perhaps the connection is idleing out?

**Comment by gmcguire** [comment]
@funkybob Can you provide a stack trace?  I'd also be interested in the details of your environment.  I take it you have `ssl=True` in your postgresql.conf?  Also, can you tell if the error clears itself or not?  (You may need to enable debug logging for `dbpool.db.backends.postgresql_psycopg2.base` to identify individual pooled connections.)

**Comment by gmcguire** [comment]
@funkybob Your issue has prodded me to add connection testing on check out (see e86144996d5ea9242a8f69cb65bf3999d6ef46e4), which might help in your situation if you don't have control over Postgres settings.  

You can pull down the latest changes with `pip install git+http://github.com/gmcguire/django-db-pool.git@95d11027aabcbc2070de05e1a955d24c3a0c9445` and set `TEST_ON_BORROW` to `True` in the `OPTIONS` dictionary to enable it.

**Comment by funkybob** [comment]
Thanks... we'll try that ASAP.

Here's a traceback [slightly sanitised :P]

```
Traceback (most recent call last):

File ".../lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
  response = middleware_method(request)
File ".../lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/api/object_wrapper.py", line 220, in __call__
  self._nr_instance, args, kwargs)
File ".../lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/hooks/framework_django.py", line 204, in wrapper
  return wrapped(*args, **kwargs)
File ".../apps/detours/middleware.py", line 122, in process_request
  domain = DetourDomain.objects.get(domain=host)
File ".../lib/python2.7/site-packages/django/db/models/manager.py", line 131, in get
  return self.get_query_set().get(*args, **kwargs)
File ".../lib/python2.7/site-packages/django/db/models/query.py", line 361, in get
  num = len(clone)
File ".../lib/python2.7/site-packages/django/db/models/query.py", line 85, in __len__
  self._result_cache = list(self.iterator())
File ".../lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
  for row in compiler.results_iter():
File ".../lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
  for rows in self.execute_sql(MULTI):
File ".../lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 817, in execute_sql
  cursor = self.connection.cursor()
File ".../lib/python2.7/site-packages/django/db/backends/__init__.py", line 308, in cursor
  cursor = util.CursorWrapper(self._cursor(), self)
File ".../lib/python2.7/site-packages/dbpool/db/backends/postgresql_psycopg2/base.py", line 160, in _cursor
  self.connection.set_isolation_level(self.isolation_level)
OperationalError: SSL SYSCALL error: EOF detected
```

**Comment by funkybob** [comment]
In watching more error reports, I'm convinced it's always the first db hit of the request.

**Comment by gmcguire** [comment]
Yes, this makes sense since you won't know the connection has dropped (due to an SSL/TCP timeout of some sort it seems) until you try and execute a query.  The call to `set_isolation_level` is the first thing Django 1.4/1.5 does after fetching a connection when the db timezone and Django timezone are the same.

One question is whether psycopg2 recognizes this when the connection is returned to the pool - which is when it inspects connections - and discards the connection, or if it remains in the pool until you restart.  If it's the latter I'd like to report it to psycopg2 for improvement.  Do the errors clear without a restart?

In either case the `TEST_ON_BORROW` code should help, as it will issue the first db query of the request and recover appropriately if needed.

**Comment by funkybob** [comment]
Given the slow rate of errors, yes, I'm confident they clear on their own.

We've deployed with the TEST_ON_BORROW feature and enabled it, and so far the errors have stopped!
